CONFIG_GPIO=y

CONFIG_BUILD_OUTPUT_HEX=y

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=n

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_RTT=y
CONFIG_USE_SEGGER_RTT=y

CONFIG_DK_LIBRARY=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

CONFIG_MAIN_STACK_SIZE=5200

CONFIG_NANOPB=y

# # UART
# CONFIG_SERIAL=y
# CONFIG_UART_ASYNC_API=y

# # BME280
CONFIG_SENSOR=y
CONFIG_CUSTOM_BME280=y

CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_RESET_ON_FATAL_ERROR=n

# LED BLINK
CONFIG_BLINK=y

# # NETWORK
CONFIG_NETWORKING=y
# CONFIG_NET_NATIVE=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_DHCPV4=y
CONFIG_DNS_RESOLVER=y
CONFIG_NET_TCP=y
CONFIG_NET_TCP_WORKQ_STACK_SIZE=2048

CONFIG_WIFI=y
CONFIG_WIFI_NM_WPA_SUPPLICANT=y
CONFIG_WIFI_NM_WPA_SUPPLICANT_LOG_LEVEL_OFF=y

CONFIG_NRF70_SR_COEX=y
CONFIG_NRF70_SR_COEX_RF_SWITCH=y
CONFIG_NRF70_RX_NUM_BUFS=16
CONFIG_NRF70_MAX_TX_AGGREGATION=4

CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_NET_MGMT_EVENT_STACK_SIZE=22000
CONFIG_NET_MGMT_EVENT_QUEUE_TIMEOUT=5000

CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_CONNECTION_MANAGER_MONITOR_STACK_SIZE=5200
CONFIG_L2_WIFI_CONNECTIVITY=y
# CONFIG_L2_WIFI_CONNECTIVITY_AUTO_CONNECT=y

CONFIG_WIFI_CREDENTIALS=y
CONFIG_WIFI_CREDENTIALS_MAX_ENTRIES=1
CONFIG_WIFI_CREDENTIALS_STATIC=n

CONFIG_NET_TC_TX_COUNT=0
CONFIG_NET_BUF_TX_COUNT=16
CONFIG_NET_BUF_RX_COUNT=16
CONFIG_NET_PKT_TX_COUNT=14
CONFIG_NET_PKT_RX_COUNT=14
CONFIG_NET_TX_STACK_SIZE=4096
CONFIG_NET_RX_STACK_SIZE=4096

CONFIG_NET_SOCKETS_SOCKOPT_TLS=y
CONFIG_TLS_CREDENTIALS=y
CONFIG_TLS_CREDENTIALS_BACKEND_PROTECTED_STORAGE=y
CONFIG_MBEDTLS_RSA_C=y

# CONFIG_SHELL=y
# CONFIG_NET_L2_WIFI_SHELL=y
# CONFIG_WIFI_CREDENTIALS_SHELL=y
# CONFIG_SHELL_STACK_SIZE=5200

# CONFIG_NET_ZPERF=y
# CONFIG_NET_CONFIG_SETTINGS=y
# CONFIG_NET_CONFIG_INIT_TIMEOUT=0
# CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.168.0.45"
# CONFIG_NET_BUF_FIXED_DATA_SIZE=y
# CONFIG_NET_BUF_DATA_SIZE=1100

# CONFIG_MQTT_HELPER=y
# CONFIG_MQTT_CLEAN_SESSION=y
# CONFIG_MQTT_SAMPLE_PUB_TOPIC="wifi/fund/board/publish/button/topic99mlokc"
# CONFIG_MQTT_SAMPLE_SUB_TOPIC="wifi/fund/board/subscribe/led/topic99mlokc"
# CONFIG_NET_BUF_FIXED_DATA_SIZE=y
# CONFIG_NET_BUF_DATA_SIZE=256
# CONFIG_MQTT_LIB_TLS=y
# CONFIG_MQTT_SAMPLE_BROKER_HOSTNAME="broker.hivemq.com"
# CONFIG_MQTT_HELPER_SEC_TAG=24
# CONFIG_MQTT_HELPER_CERTIFICATES_FOLDER="application/credentials"

# BLE
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=75
CONFIG_BT_WIFI_PROV=y
CONFIG_WIFI_PROV_CORE=y
CONFIG_BT_BONDABLE=n

CONFIG_BT_SMP=y
CONFIG_BT_BUF_ACL_RX_SIZE=151
CONFIG_BT_L2CAP_TX_MTU=147
CONFIG_BT_BUF_ACL_TX_SIZE=151
CONFIG_BT_RX_STACK_SIZE=22000
CONFIG_BT_DEVICE_NAME_DYNAMIC=y

# BT enables MbedTLS heap but uses the default heap size which is not enough for Wi-Fi.
CONFIG_MBEDTLS_HEAP_SIZE=12000

CONFIG_NET_PKT_BUF_TX_DATA_POOL_SIZE=5000
CONFIG_NET_PKT_BUF_RX_DATA_POOL_SIZE=5000

# NVS
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y

CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y

# # DFU
# # CONFIG_BOOTLOADER_MCUBOOT=y
# # CONFIG_MCUMGR=y
# # CONFIG_MCUMGR_GRP_OS=y
# # CONFIG_MCUMGR_GRP_IMG=y
# # CONFIG_MCUMGR_TRANSPORT_UART=y
# # CONFIG_NET_BUF=y
# # CONFIG_ZCBOR=y
# # CONFIG_CRC=y
# # CONFIG_FLASH=y
# # CONFIG_IMG_MANAGER=y
# # CONFIG_STREAM_FLASH=y
# # CONFIG_FLASH_MAP=y
# # CONFIG_BASE64=y

# # CONFIG_SPI=y
# # CONFIG_SPI_NOR=y
# # CONFIG_SPI_NOR_SFDP_DEVICETREE=y
# # CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
# # # QSPI drivers are enabled by defualt for some chips.
# # # Disable it explicitly to be sure QSPI is disabled.
# # CONFIG_NORDIC_QSPI_NOR=n 
