# SB_CONFIG_BOOTLOADER_MCUBOOT=y
# SB_CONFIG_MCUBOOT_MODE_SINGLE_APP=n
# SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APP_DIR}/private_key.pem"
# SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y

# SB_CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y
# SB_CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y

SB_CONFIG_WIFI_NRF70=y

